apiVersion: batch/v1
kind: CronJob
metadata:
  name: acf
  labels: 
    purpose: job
spec:
  schedule: "*/5 * * * *"
  jobTemplate: 
    metadata: 
    backoffLimit: 3
    template:
      metadata:
        name: kalayan
        labels: 
          name: kalayanlabel.yaml 
      spec:
        containers:
          - name: babu
            image: nginx:1.25    
            ports:
              - containerPort: 80
                protocol: TCP 