apiVersion: batch/v1
kind: CronJob
metadata:
  name: acf
  labels: 
    name: acflabel.yaml
spec:
  schedule: "*/5 * * * *"
  jobTemplate: NO
    metadata: NO
    backoffLimit: 3
  selector:
    matchLabels: 
      name: pavanlabel.yaml
    template:
      metadata:
        name: kalayan
        labels: 
          name: kalayanlabel.yaml 
      spec:
        containers:
          - name: babu
            image: nginx:1.25    
            ports:
              - containerPort: 80
                protocol: TCP 