apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  labels: 
    name: job
spec:
  schedule: "*/5 * * * *"
  jobTemplate: 
    metadata:
      labels:
        name: jobs
    spec:    
      backoffLimit: 3
      template:
        metadata:
          labels: 
            name: batch
        spec:
          containers:
            - name: babu
              image: nginx:1.25   
              command:
                - sleep
                - 1d\
          restartPolicy: OnFailure      