apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  labels: 
    purpose: job
spec:
  schedule: "*/5 * * * *"
  jobTemplate: 
    metadata:
      labels:
        name: pavanlabel.yaml
    spec:    
      backoffLimit: 3
      template:
        metadata:
          labels: 
            name: kalayanlabel.yaml 
        spec:
          containers:
            - name: babu
              image: alpine    
              command:
                - sleep
                  1d