apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      name: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable:  25%  
  template:
    metadata:
      labels:
        name: true
    spec:
      containers:
        - name: false
          image: shaikkhajaibrahim/nopcommerceaug23
          ports:
            - containerPort: 80
              protocol: TCP    
        