---
apiVersion: v1
kind: pod
metadata: 
  name: manohar
  labels: manohars1
spec:
  - containers:
      name: pspk
      image: nginx1.25
      ports:
        - ContainerPort: 80
          protocol:  TCP
       
