apiVersion: v1
kind: Pod
metadata:
  name: kalayan
  labels: 
    app: kalayan
    env: dev
    release: v1.1
spec:
  containers:
    - name: poni 
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP