---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: varun
  labels: 
    name: varunlabel
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      name: varunlabel
  template:
    metadata:
        labels:
          name: varunlabel 
    spec:
      containers:
        - name: asus
          image: nginx:1.25
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: 	v1
kind: Service
metadata:
  name: ram
  labels:
    name: shop  
spec:
  selector:
    name: plain
  ports:
    - port: 80
      targetPort: 80            