apiVersion: v1
kind: Service
metadata:
  name: varunlabel
  labels:
    name: toomuch
spec:
  type: NodePort
  selector:
    name: toomuch
  ports:
    - nodePort: 32334
      port: 80
      targetPort: 80
         