apiVersion: v1
kind: Service
metadata:
  name: sai
  labels:
    name: toomuch
spec:
  type: NodePort
  selector:
    name: toomuch
  ports:
    - nodePort: 3334
      port: 8080
      targetPort: 8080
      protocol: TCP    