---
apiVersion: v1
kind: Service
metadata:
  name: varunlabel
  labels: 
    name: 
spec:
  selector:
    name: varunlabel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

--- 
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service-endpoints
subsets:
  - addresses:
      - ip: 10.244.1.70
      - ip: 10.244.1.73
      - ip: 10.244.1.72 # Replace with the actual IP addresses of your pods
    ports:
      - port: 80           # Replace with the port number your service is listening on
        name: http
