---
apiVersion: v1
kind: Service
metadata:
  name: ram
  labels: 
    name: shop
spec:
  selector:
    name: plain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: ClusterIP    