apiVersion: v1
kind: Pod
metadata:
  name: kalayan-pods-label-1
  labels: 
    app: kalayan
    env: dev
spec:
  containers:   
    - name: suresh 
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
    - name: ramesh
      image: alpine
      args:
        - sleep
        - 1d       