apiVersion: v1
kind: Pod
metadata:
  name: kalayan-pods-label-1
  labels: 
    app: kalayan
    env: dev
    release: v1.1
spec:
  containers:
    - name: suresh 
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
    - name: ramesh
      image: nginx
      args:
        - sleep
          1d       