--- 
apiVersion: v1
kind: Pod
metadata: 
  name: kalayanbabu
spec:
  containers:
    - name: kalayan
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP
    - name: babu
      image: alpine
          args:
            - sleep
            - 1day  